import axios from "axios";

const API_URL = "http://localhost:5000/api";

export const registerUser = async (username: string | undefined, email: string, password: string) => {
  try {
    const response = await axios.post(`${API_URL}/signup`, { username, email, password });
    console.log(response, "response from auth.ts upon registering a new user from client");
    return response.data; //this is the token generated by the backend Signup controller handler
  } catch (error) {
    console.error("Error signing up", error);
    throw error;
  }
};

export const loginUser = async (password: string, email: string) => {
  try {
    const response = await axios.post(`${API_URL}/login`, { password, email });
    return response.data;
  } catch (error) {
    console.error("Error signing up", error);
    throw error;
  }
};
